image: continuumio/miniconda3:latest

default:

  before_script:
    - conda create -y -n test python=3.7 numpy
    - export PATH="$(dirname $(conda run -n test which python)):$PATH";

  script:
    - python setup.py sdist
    - pip install dist/*
    - python tests/test_suite.py

  after_script:
      - conda remove --all -y -n test
      - rm -rf builds
